[languages.zh]
label = "中文"
direction = "ltr"
title = "A Moment's Rest"
weight = 1
contentDir = "content/zh"
[[languages.zh.menus.main]]
url = "/zh/"
identifier = "home"
name = "Home"
weight = -10
[languages.zh.menus.main.params]
icon = "home"
[languages.zh.permalinks]
[languages.zh.permalinks.page]
path = "/:sections/:contentbasename/"
[languages.zh.permalinks.section]
path = "/:contentbasename/"

[languages.en]
label = "English"
direction = "ltr"
title = "A Moment's Rest"
weight = 2
contentDir = "content/en"
[[languages.en.menus.main]]
url = "/en/"
identifier = "home"
name = "Home"
weight = -10
[languages.en.menus.main.params]
icon = "home"
[languages.en.permalinks]
[languages.en.permalinks.page]
path = "/:sections/:contentbasename/"
[languages.en.permalinks.section]
path = "/:contentbasename/"
