// codeBlockLang.ts
// Maps Chroma language identifiers to human-readable display labels.
// Add or adjust entries here whenever a new language needs a custom label.

const LANG_LABELS: Record<string, string> = {
  go:         'Go',
  js:         'JavaScript',
  javascript: 'JavaScript',
  ts:         'TypeScript',
  typescript: 'TypeScript',
  jsx:        'JSX',
  tsx:        'TSX',
  py:         'Python',
  python:     'Python',
  rb:         'Ruby',
  ruby:       'Ruby',
  rs:         'Rust',
  rust:       'Rust',
  cpp:        'C++',
  'c++':      'C++',
  c:          'C',
  cs:         'C#',
  java:       'Java',
  kt:         'Kotlin',
  kotlin:     'Kotlin',
  swift:      'Swift',
  sh:         'Shell',
  bash:       'Bash',
  zsh:        'Zsh',
  fish:       'Fish',
  ps1:        'PowerShell',
  powershell: 'PowerShell',
  html:       'HTML',
  css:        'CSS',
  scss:       'SCSS',
  sass:       'Sass',
  less:       'Less',
  json:       'JSON',
  yaml:       'YAML',
  yml:        'YAML',
  toml:       'TOML',
  xml:        'XML',
  sql:        'SQL',
  md:         'Markdown',
  markdown:   'Markdown',
  dockerfile: 'Dockerfile',
  docker:     'Docker',
  makefile:   'Makefile',
  make:       'Make',
  lua:        'Lua',
  vim:        'Vim',
  r:          'R',
  dart:       'Dart',
  php:        'PHP',
  perl:       'Perl',
  scala:      'Scala',
  haskell:    'Haskell',
  elixir:     'Elixir',
  erlang:     'Erlang',
  graphql:    'GraphQL',
  terraform:  'Terraform',
  ini:        'INI',
  console:    'Console',
  text:       'Text',
  plaintext:  'Text',
};

export function getDisplayLang(raw: string): string {
  const key = raw.toLowerCase().replace(/^language-/, '');
  return LANG_LABELS[key] ?? key.toUpperCase();
}
